### PR TITLE
Fill out a lot of resource definitions

### PR DESCRIPTION
**Pull request by piepie62**
This renames and fixes a bunch of typing issues that existed in my first PR of resource information. There are a couple questions I'd like to ask about this, though:

First, there are a couple seemingly polymorphic subobjects and/or contained objects. How should those be handled, if at all? I just don't understand the proxy system (and specifically how std::variant seems to interact with it) enough to figure that out.
Second, and related, AnimationBlueprints have a field where their type is actually specified as a string in the LSF file. Have you seen something like that before, and if so is there a structure to deal with it? The structure ends up looking like [this](https://github.com/Norbyte/bg3se/compare/main...piepie62:bg3se:main#diff-b4af7dd78affe101fec940fed20f82287aaf2e506ea081ddfef0014705ccd30dR262-R266), where Type is some sort of pointer.

Finally, a few structures, for some reason, have a back-reference to their containing structure. I currently exposed that model to the Lua code, but am not sure whether that is desirable, considering that it inserts some otherwise strange differences into the structures (see BlendSpace and FCurve). Should that stay modeled as such or should I remove it? Part of what I'm annoyed about there is just the extra layer of tables necessary to access their data, to be quite honest.

### CODE REVIEW

**Comment by Norbyte** [comment]
Regarding std::variant, there is no extra work that needs to be done, since the serializer code will iterate all possible variants and push whichever is actually in the variant.

For exposing polymorphic classes I haven't added the type selection code yet that would allow doing a polymorphic value push to Lua, so fuor now only parent classes are visible to script, but this is coming soon :tm:.

The AnimationBlueprint one is a bit like how root template polymorphism works, if its type is `"character"` then it can be casted to an eoc::CharacterTemplate, etc.

For unnecessary recursion you can just add [[bg3::hidden]] to the property if it adds no value otherwise.
There are some cases where it is desirable for script to be able to jump to the parent, but in these cases it is just some internal code organization jank that needs this, but not script.

**Comment by Norbyte** [comment]
This is sort of what polymorphic push will look like:
https://github.com/Norbyte/ositools/blob/master/ScriptExtender/Lua/Server/LuaServer.cpp#L205

**Comment by piepie62** [comment]
I'm nearing the end of this slog of RE; I've just got a couple that today I decided I didn't want to deal with yet. Pushed just now because it's just a lot of stuff that I don't want to accidentally lose if I do something funky with git

**Comment by Norbyte** [comment]
I'll add the polymorphic object push code this weekend, so it should be able to proxy the proper type to Lua.

**Comment by piepie62** [comment]
The one issue I have right now from a perspective of "how do I do this" is not your fault but instead BG3's: the BG3Variant struct has its own serialization and deserialization code that works only with strings. Should I just push a string, a table of type name and the value as a string, or figure out some way to build a native representation?

**Comment by Norbyte** [comment]
All variants used in bg3 are literally an `std::variant` which has serialization support in SE

**Comment by Norbyte** [comment]
Unless you mean something else I didnt't see yet 🤔

**Comment by piepie62** [comment]
I do mean something else you haven't seen yet; see [this structure](https://github.com/Norbyte/bg3se/pull/113/commits/c0ebda93e40840f4504788000d52c16a8e0b580a#diff-b4af7dd78affe101fec940fed20f82287aaf2e506ea081ddfef0014705ccd30dR107). I'm fairly certain that's not how std::variant works; I just have no idea what to call it other than "BG3-specific variant", so "BG3Variant" was the name I came up with.

**Comment by Norbyte** [comment]
Oh yea, that is not a normal variant, it is a variant type specific to the animation blending system (Genome).
This structure looked like this in DOS2:

```c
struct gn::GenomeVariant
{
  void* Value;
  gn::GenomeVarTypeDesc *Type;
};

struct gn::GenomeVarTypeDesc
{
  void (*AssignFromVariantFunctor)(gn::GenomeVariant*, gn::GenomeVariant*);
  void (*AssignFromRawValueFunctor)(gn::GenomeVariant*, void*);
  void* UnknownFunctor;
  void (*ParseFromStringFunctor)(gn::GenomeVariant*, char const*);
  void (*StringifyFunctor)(gn::GenomeVariant*, STDString*);
  void (*DestructorFunctor)(void*);
  uint32_t TypeHash;
  uint64_t ValueSize;
  uint64_t Flags;
  FixedString Name;
  bool field_50;
  gn::GenomeVariant* Default;
};


```

**Comment by Norbyte** [comment]
Unless you want to spend too much time on it, just use the stringify/parse functor of the game to convert it into Lua values

**Comment by piepie62** [comment]
Been looking into how I would do that properly- I honestly have no idea how most of the Lua interface works, and ccan't figure out how to "replace" the variant with the string values. Do you have any tips?

**Comment by Norbyte** [comment]
Hm, what you can probably do in this case is mark the Value property on the variant as `[[bg3::hidden]]` and define the property as something that has a getter and setter function with `P_GETTER_SETTER(Value, GetValue, SetValue)`, then define the string serialize/unserialize logic within the GetValue and SetValue methods.

**Comment by Norbyte** [comment]
Or just leave it to me and I'll figure something out :)

**Comment by Norbyte** [comment]
Some info for AnimationEventPropertyType - these were the types in DOS2:
1 = TextKeySoundType
2 = TextKeyEffectType
3 = TextKeyFootStepType
4 = TextKeyAttachType
5 = TextKeyHandSoundType
6 = TextKeyWeaponEffectType
7 = TextKeyGenomeType
8 = TextKeyAttackType
9 = TextKeyRagdollType
10 = TextKeyVisualCullFlagType

**Pull request merged**
